name: Start Digital
favicon: null
layout_spectrum: 0.3328753656242043
typography_spectrum: 0.7988392687402666
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.07913572201505303
  lightness: 0.20323330932296813
  saturation: 0.6769562365952879
  rhythmicContrast: 0.07687423145398498
purpose: []
