name: Start Digital
favicon: null
layout_spectrum: 0.49388
typography_spectrum: 0.1418
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f7f8'
    - '#e97365'
    - '#791210'
    - '#263032'
    - '#9d4a48'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
purpose: []
